apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: my-config1

replicas:
  - name: nginx-deployment
    count: 5
