apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: nginx-demo
    repoURL: https://github.com/maxhaeger/helm-kustomize-demo.git
    targetRevision: master
    directory:
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

