apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config1
  namespace: {{ .Release.Namespace }}
  labels:
    app: nginx
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  index.html: |
{{ .Values.configMap.data.index.html | indent 4 }}
