apiVersion: v1
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>A simple HTML document</title>
    </head>
    <body>
        <p>This is Deployment One!<p>
    </body>
    </html>
kind: ConfigMap
metadata:
  name: my-config1
  namespace: default
